+++
title = "Redis Client lettuce 3.1 Final released"
date = "2015-03-28T20:15:14"
lastmod = "2025-01-03T22:49:03"
draft = false
slug = "redis-client-lettuce-3-1-final-released"
wordpress_id = "210"
url = "/2015/03/28/redis-client-lettuce-3-1-final-released/"
categories = ["Blog"]
+++
This release introduces support for SSL, enables lambda expressions on streaming channels and a lot of bugfixes and resilience changes. +
lettuce extensibility is improved. You can override certain parts of the client to supply classes (connection classes) that behave the way you need by extending RedisClient or RedisClusterClient. +
You can reset the internal connection state in case you run into broken connections (invalid connection state due to SSL tunneling or others) by calling the reset() method on your connection.

<!--more-->

lettuce is now built with Java 8 but can be used with Java 6, 7 and 8. Java 6 and 7 support will be dropped with lettuce 4.0. The new lettuce-testcontainer project ensures until then. You can find the build results at https://travis-ci.org/mp911de/lettuce-testcontainer

lettuce is also now on Gitter. If you need any support, meet lettuce at https://gitter.im/mp911de/lettuce

== SSL Support

SSL support for Redis means that you need a Redis that is behind some SSL tunnel (mostly stunnel). You can use this feature with Java 6, 7 and 8. The only issue using Java 6 is that you won't be able to verify the Redis host name against the SSL certificate. Redis with SSL works only in a sane way when you use standalone Redis. Sentinel and Redis Cluster provide host and port details, and since Redis has no out-of-the-box SSL support you would always connect to the unencrypted ports even your first connection to Sentinel or Cluster was encrypted.

SSL and StartTLS are supported; Client certificates are not supported.

See https://github.com/mp911de/lettuce/wiki/SSL-Connections for details on SSL connections.

== Enhancements

* Change build environment to JDK8 https://github.com/mp911de/lettuce/issues/49[++#++49]
* Allows lambda expressions on streaming channels enhancement https://github.com/mp911de/lettuce/issues/47[++#++47]
* JavaDoc compatibility with Java 8 https://github.com/mp911de/lettuce/issues/39[++#++39]
* Add cluster commands: Readonly, and clusterNodes https://github.com/mp911de/lettuce/pull/38[++#++38] (for standalone) (Thanks to https://github.com/taer[@taer])
* Add RedisFuture return to RedisPubSubConnection API enhancement https://github.com/mp911de/lettuce/issues/34[++#++34]
* Provide API and visibility in order to extend RedisClient and its connections https://github.com/mp911de/lettuce/issues/33[++#++33]
* SSL support enhancement and improved channel initialization https://github.com/mp911de/lettuce/issues/28[++#++28]
* Allow reset on internal connection state enhancement https://github.com/mp911de/lettuce/issues/25[++#++25]
* Enhance lettuce resilience enhancement https://github.com/mp911de/lettuce/issues/24[++#++24]
* Add jsr305 annotation lib https://github.com/mp911de/lettuce/issues/45[++#++45]

== Fixes

* Fix synchronized issue enhancement https://github.com/mp911de/lettuce/pull/44[++#++44] (Thanks to https://github.com/taer[@taer])
* RedisClusterConnection stops operation after https://github.com/mp911de/lettuce/issues/42[++#++42] (Thanks to https://github.com/taer[@taer])
* Fix time conversion for timeout settings https://github.com/mp911de/lettuce/pull/36[++#++36] (Thanks to https://github.com/taer[@taer])
* Pool return no longer nulls connection https://github.com/mp911de/lettuce/pull/35[++#++35] (Thanks to https://github.com/taer[@taer])
* Fix Method Signature RedisClient.connectPubSub bug https://github.com/mp911de/lettuce/issues/23[++#++23]
* Fix URL parsing https://github.com/mp911de/lettuce/issues/32[++#++32]

lettuce requires a minimum of Java 8 to build and Java 6 run. It is tested continuously against Redis 3.0.

== Links

* https://github.com/mp911de/lettuce/releases/tag/3.1.Final[Release on Github]
* http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22biz.paluch.Redis%22%20AND%20a%3A%22lettuce%22[Artifact overview on Maven Central]
* http://search.maven.org/remotecontent?filepath=biz/paluch/Redis/lettuce/3.1.Final/lettuce-3.1.Final.jar[Download lettuce 3.1.Final]
* https://github.com/mp911de/lettuce/wiki[Wiki]
* http://redis.paluch.biz[Maven Site (Javadoc)]

Maven coordinates:

[source,xml]
----
<dependency>
    <groupId>biz.paluch.redis</groupId>
    <artifactId>lettuce</artifactId>
    <version>3.1.Final</version>
</dependency>

<dependency>
    <groupId>biz.paluch.redis</groupId>
    <artifactId>lettuce</artifactId>
    <version>3.1.Final</version>
    <classifier>shaded</classifier>
</dependency>
----

Any feedback is appreciated or create https://github.com/mp911de/lettuce/issues[issues on GitHub].
