+++
title = "Redis Client lettuce 3.2 Beta1 released"
date = "2015-05-16T14:45:57"
lastmod = "2025-01-03T22:49:03"
draft = false
slug = "redis-client-lettuce-3-2-beta1-released"
wordpress_id = "213"
url = "/2015/05/16/redis-client-lettuce-3-2-beta1-released/"
categories = ["Blog"]
+++
This release features Unix domain sockets on linux-x86++_++64 systems. Local connections to a Redis instance are now possible without the use of the network. A second feature with a huge impact is client options. Client options allow to control behavior on a fine-grained base. It is now possible to turn off auto-reconnect, validate the connection with a PING before activating the connection for client usage and many more.

<!--more-->

We tested lettuce using YourKit for performance. Subtracting all IO the most time is spent on constructing the return futures and command objects. The async API can issue about 300Kops/sec whereas the sync API performs about 13Kops/sec (GET's, PING's) on a single thread. Sync performance depends on the Redis performance (tested on a Mac, 2,7 GHz Intel Core i7).

lettuce provides now also base functionality for building clients using the Redis protocol. An example is spinach (https://github.com/mp911de/spinach).

lettuce is built with Java 8 but can be used with Java 6, 7 and 8. Java 6 and 7 support will be dropped with lettuce 4.0. The new lettuce-testcontainer project ensures until then. You can find the build results at https://travis-ci.org/mp911de/lettuce-testcontainer

If you need any support, meet lettuce at https://gitter.im/mp911de/lettuce

From now on, mp911de/lettuce is a standalone repo that is no longer a Github fork of wg/lettuce. On code and IP-level, it is of course it is the fork of wg/lettuce. This Github fork flag prevented searching for code and searches for lettuce did not show up the repo itself. The change is only, how Github handles the repo, everything else stays the same.

== Unix Domain Sockets

Unix Domain Sockets are useful only if connecting locally and maintaining the connection point on your own. Using RedisClusterClient with Unix Domain Sockets would connect to the local node using a socket and then open TCP connection to all the other hosts. A good example is connecting locally to a standalone or a single cluster node to gain performance.

Unix Domain Socket connections are currently only available to Linux x86++_++64 systems with a minimum netty version of 4.0.26.Final. You can, however, port the native library to your system. The netty guys would appreciate.

See https://github.com/mp911de/lettuce/wiki/Unix-Domain-Sockets

== Enhancements

* Provide an option to connect to Redis via Unix Domain Sockets https://github.com/mp911de/lettuce/issues/52[++#++52]
* Add new cluster command MYID https://github.com/mp911de/lettuce/pull/53[++#++53] (Thanks to https://github.com/taer[@taer])
* Expose futures of re-subscription on reconnect https://github.com/mp911de/lettuce/issues/62[++#++62] (Thanks to https://github.com/kichik[@kichik])
* Ping before connect https://github.com/mp911de/lettuce/pull/61[++#++61] (Thanks to https://github.com/kichik[@kichik])
* Introduce ClientOptions to control specific behavior https://github.com/mp911de/lettuce/issues/58[++#++58]
* Enhance stability when reconnecting https://github.com/mp911de/lettuce/issues/56[++#++56]
* Extract and use interfaces for improved extensibility

== Fixes

* RedisPubSubConnectionImpl.activated does not call super.activated() https://github.com/mp911de/lettuce/issues/55[++#++55]
* RedisPubSubConnectionImpl.activated() deadlock https://github.com/mp911de/lettuce/issues/57[++#++57]

== Other

* Inspect lettuce using YourKit https://github.com/mp911de/lettuce/issues/54[++#++54]

lettuce requires a minimum of Java 8 to build and Java 6 run. It is tested continuously against Redis 3.0.

== Links

* https://github.com/mp911de/lettuce/releases/tag/3.2.Beta1[Release on Github]
* http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22biz.paluch.redis%22%20AND%20a%3A%22lettuce%22[Artifact overview on Maven Central]
* http://search.maven.org/remotecontent?filepath=biz/paluch/redis/lettuce/3.2.Beta1/lettuce-3.2.Beta1.jar[Download lettuce 3.2.Beta1]
* https://github.com/mp911de/lettuce/wiki[Wiki]
* http://redis.paluch.biz[Maven Site (Javadoc)]

Maven coordinates:

[source,xml]
----
<dependency>
    <groupId>biz.paluch.redis</groupId>
    <artifactId>lettuce</artifactId>
    <version>3.2.Beta1</version>
</dependency>

<dependency>
    <groupId>biz.paluch.redis</groupId>
    <artifactId>lettuce</artifactId>
    <version>3.2.Beta1</version>
    <classifier>shaded</classifier>
</dependency>
----

Any feedback is appreciated or create https://github.com/mp911de/lettuce/issues[issues on GitHub].
