+++
title = "Redis Client lettuce 3.0.Beta2 released"
date = "2014-07-15T19:12:18"
lastmod = "2025-01-03T22:49:13"
draft = false
slug = "redis-client-lettuce-3-0-beta2-released"
wordpress_id = "124"
url = "/2014/07/15/redis-client-lettuce-3-0-beta2-released/"
categories = ["Blog"]
+++
This release is intended to be the last beta release of lettuce. As soon as Redis 3.0 goes final, I'll release the final of lettuce 3.0.

This release contains:

* Documentation (Javadoc and Wiki)
* Improved test stability for a stable and reproducible build
* Changed redis ports from 63xx to 64xx for testing
* Fixed clientKill because of changed clientList output
* Adjusted resource cleanup to prevent memory leaks
* Prevent refCnt exceptions in case of parallel close & read
* Fixed PubSub API
* Fixed command leaking when client is not yet online/disconnected and commands are issued while the client is in the re-connect phase
* Code cleanup, fixing sonar violations
* Support for SENTINEL MASTERS command
* Support for DEBUG SEGFAULT command
* Support for PUBSUB command
* Support for sorted set commands ZLEXCOUNT, ZRANGEBYLEX, ZREMRANGEBYLEX
* Minor fixes like typos, maven site on http://redis.paluch.biz

https://coveralls.io/r/mp911de/lettuce?branch=master[image:/images/external/img/lettuce.svg[Coverage Status]]

== Links

* https://github.com/mp911de/lettuce/releases/tag/3.0.Beta2[Release on Github]
* http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22biz.paluch.redis%22%20AND%20a%3A%22lettuce%22[Artifact overview on Maven Central]
* http://search.maven.org/remotecontent?filepath=biz/paluch/redis/lettuce/3.0.Beta2/lettuce-3.0.Beta2.jar[Download lettuce-3.0.Beta2]
* https://github.com/mp911de/lettuce/wiki[Wiki]
* http://redis.paluch.biz[Maven Site/Javadoc]

Maven coordinates:

[source,xml]
----
<dependency>
    <groupId>biz.paluch.redis</groupId>
    <artifactId>lettuce</artifactId>
    <version>3.0.Beta2</version>
</dependency>
----

Any feedback is appreciated or create https://github.com/mp911de/lettuce/issues[issues on GitHub].
